
title: Nicholas Danes
show_excerpts: false # show excerpts on blog
ignore_theme_config: true
date_format: "%Y-%m-%d"

timezone: America/Denver
permalink: /blog/:year/:month/:day/:slug/

header_pages:
 - about.markdown
 - now.markdown
 - archive.markdown

# Build settings
url: "https://ndanes.com"
plugins:
  - jekyll-tidy
